environment:
  id: 7jne0
  domain: sandbox.wasp.silvios.me

  cluster:
    name: wasp-7jne0

    ingress:
      type: azure
      class: azure-application-gateway

    certificates:
      type: letsencrypt
      server: staging
