argo-cd:
  fullnameOverride: "argocd"
  server:
    config:
      url: https://argocd.example.com
      users.anonymous.enabled: "false"

  redis-ha:
    enabled: false

  controller:
    enableStatefulSet: false

  server:
    autoscaling:
      enabled: false
      minReplicas: 2

  repoServer:
    autoscaling:
      enabled: false
      minReplicas: 2
