---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-virtual-service-public
spec:
  hosts:
    - httpbin.{{ .Values.dns.cname }}.{{ .Values.dns.domain }}

  gateways:
    - istio-ingress/public-ingress-httpbin

  http:
    - match:
        - scheme:
            exact: http
          uri:
            regex: "^/(([^\\.].*)|(\\.[^w].*)|(\\.w[^e].*)|(\\.we[^l].*)|(\\.wel[^l].*)|(\\.well[^\\-].*))"
      redirect:
        scheme: https
        redirectCode: 302 # 302 to not mess with risky permanent redirections since a workaround

    - name: httpbin
      headers:
        request:
          add:
            X-A1-origin-1: public-ingress-httpbin

      route:
        - destination:
            host: httpbin.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
