{{- range $server :=  .Values.letsencrypt.servers }}
{{- range $issuer := $.Values.letsencrypt.issuers }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ $server.name }}-{{ $issuer.name }}
spec:
  acme:
    email: {{ $.Values.letsencrypt.email }}
    server: https://{{ $server.host }}.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-{{ $server.name }}-{{ $issuer.name }}-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: {{ $issuer.class }}
{{- end }}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
