#!/bin/bash
expression="${1}"

echo "AKS Cluster (waiting for ProvisioningState become Succeeded)"
echo ""

az aks list --output table \
| grep -E "Name|^----|${expression}"

cluster_line=$(
  az aks list \
    --query "[?contains(name, \`${expression}\`) && provisioningState=='Succeeded'].[name, resourceGroup]" \
    --output tsv
)

if [ -z "${cluster_line}" ]; then
  exit 1
fi

aks_cluster_name=$(awk -F'\t' '{ print $1 }' <<< "${cluster_line}")
aks_cluster_resource_group_name=$(awk -F'\t' '{ print $2 }' <<< "${cluster_line}")

echo ""
echo "Getting credentials for AKS Cluster ${aks_cluster_name} [Resource Group: ${aks_cluster_resource_group_name}]..."
echo ""

if ! grep --quiet "^clusters:" ~/.kube/config; then
  echo "clusters: []" >> ~/.kube/config
fi

if ! az aks get-credentials \
  --name "${aks_cluster_name}" \
  --resource-group "${aks_cluster_resource_group_name}" \
  --overwrite-existing \
  --admin &> /dev/null; then
  echo "Failed to get credentials for ${aks_cluster_name}"
  exit 1
fi

exit 0
