#!/bin/bash
EXPRESSION=${1}

CACHE_FILE=$(mktemp)

echo "AKS Cluster (ProvisioningState must be Succeeded)"
echo ""

az aks list --output table \
| grep -E "Name|^----|${EXPRESSION}" \
| tee "${CACHE_FILE?}"

grep \
  --quiet "${EXPRESSION?}.*Succeeded" "${CACHE_FILE?}"

if [ "$?" == 0 ]; then
  az aks get-credentials \
    --name "${EXPRESSION?}" \
    --resource-group "${EXPRESSION?}" \
    --overwrite-existing \
    --admin &> /dev/null

  exit 0
fi

exit $?
