#!/bin/bash
EXPRESSION=${1}

CACHE_FILE=$(mktemp)

echo "AKS Cluster (waiting for ProvisioningState become Succeeded)"
echo ""

az aks list --output table \
| grep -E "Name|^----|${EXPRESSION}" \
| tee "${CACHE_FILE?}"

grep \
  --quiet "${EXPRESSION?}.*Succeeded" "${CACHE_FILE?}"

RESULT=$?

if [ "${RESULT}" == 0 ]; then
  LINE=$(grep "${EXPRESSION?}.*Succeeded" "${CACHE_FILE?}")

  AKS_CLUSTER_NAME=$(                awk '{ print $1 }' <<< "${LINE}")
  AKS_CLUSTER_RESOURCE_GROUP_NAME=$( awk '{ print $3 }' <<< "${LINE}")

  echo ""
  echo "Getting credentials for AKS Cluster ${AKS_CLUSTER_NAME} [Resource Group: ${AKS_CLUSTER_RESOURCE_GROUP_NAME}]..."
  echo ""

  if ! grep --quiet "^clusters:" ~/.kube/config; then
    echo "clusters: []" >> ~/.kube/config
  fi

  az aks get-credentials \
    --name "${AKS_CLUSTER_NAME?}" \
    --resource-group "${AKS_CLUSTER_RESOURCE_GROUP_NAME?}" \
    --overwrite-existing \
    --admin &> /dev/null

  exit 0
fi

exit ${RESULT}
