#!/bin/bash
this_script_directory="${0%/*}"
PATH="${PATH}:${this_script_directory}"

check-kubernetes-access

if [ "$?" -ne 0 ]; then
  exit 1
fi

kubectl \
  --namespace argocd \
  get configmap argocd-cm \
  --output jsonpath='{.data.url}' \
  --ignore-not-found \
| sed 's|https://||'
