#!/bin/bash
CACHE_FILE=$(mktemp)

kubectl \
  --namespace argocd \
  get ing argocd-server \
  --output jsonpath='{.spec.rules[0].host}' \
  --ignore-not-found > "${CACHE_FILE?}"

cat "${CACHE_FILE?}"
