#!/bin/bash
desired_pod_count="${1?}"

running_pod_count=$(
  kubectl \
    --namespace argocd \
    get pods \
    --ignore-not-found \
| grep -E "^argocd.*1/1.*Running" \
| wc -l
)

echo "argo-cd Running PODs: ${running_pod_count} (expected: ${desired_pod_count})"

desired_pod_count_to_compare=$((desired_pod_count - 1))

if [ "${running_pod_count}" -gt "${desired_pod_count_to_compare}" ]; then
  exit 0
fi

exit 1
