#!/bin/bash
CACHE_FILE=$(mktemp)

ARGOCD_HOST=$1

curl \
  --insecure \
  --silent \
  --output /dev/null \
  --head \
  --write-out "%{http_code}" \
  https://${ARGOCD_HOST?} > "${CACHE_FILE?}"

HTTP_CODE=$(cat "${CACHE_FILE?}")

if [ "${HTTP_CODE}" == "200" ]; then
  exit 0
fi

exit 1
