#!/bin/bash
this_script_directory="${0%/*}"
PATH="${this_script_directory}:${PATH}"

host_under_test="${1}"

: "${EXECUTION_CACHE_FILE:=$(mktemp)}"

record_check_curl="curl_check:${host_under_test}:"

printf "curl-check (%s) " "${host_under_test}"

if [ -z "${host_under_test}" ]; then
  exit 1
fi

check_if_host_return_200() {
  check-curl "${host_under_test?}"

  echo "${record_check_curl}: $?"
}

check_if_host_return_200 >> "${EXECUTION_CACHE_FILE}"

record_check_curl_success_count=$(grep -E "${record_check_curl}: 0" "${EXECUTION_CACHE_FILE}" | wc -l)
record_check_curl_failure_count=$(grep -E "${record_check_curl}: 1" "${EXECUTION_CACHE_FILE}" | wc -l)

printf "[ok=%s fail=%s] " "${record_check_curl_success_count}" "${record_check_curl_failure_count}"
echo ""

if [ "${record_check_curl_success_count}" -gt 2 ]; then
  exit 0
fi

exit 1
