#!/bin/bash
host_under_test="${1?}"

http_code=$(
  curl \
    --insecure \
    --silent \
    --output /dev/null \
    --head \
    --write-out "%{http_code}" \
    "https://${host_under_test}"
)

if [ "${http_code}" == "200" ]; then
  exit 0
fi

exit 1
