#!/bin/bash
regex="${1?}"
count="${2:-1}"

cache_file=$(mktemp)
trap 'rm -f "${cache_file}"' EXIT

echo "certificates (Regex: \"${regex}\" ${count})"
echo ""

kubectl get certificates -A \
| grep -E "NAME|${regex}|^ " \
| tee "${cache_file?}"

echo ""

kubectl get ingress -A \
| grep -E "NAME|${regex}|^ " \
| tee -a "${cache_file?}"

certificates_ready_count=$(
grep -E "${regex}.*True" "${cache_file?}" \
| wc -l
)

count_to_compare=$((count - 1))

if [ "${certificates_ready_count}" -gt "${count_to_compare}" ]; then
  exit 0
fi

exit 1
