#!/bin/bash
host_under_test="${1}"

: "${EXECUTION_CACHE_FILE:=$(mktemp)}"

record_check_google="dns_check_google"
record_check_local="dns_check_local"

check_if_dns_is_resolvable_using_google() {
  dig @8.8.8.8 "${host_under_test}" \
| grep "^${host_under_test}" > /dev/null

  echo "${record_check_google}: $?"
}

check_if_dns_is_resolvable_locally() {
  dig "${host_under_test}" \
| grep "^${host_under_test}" > /dev/null

  echo "${record_check_local}: $?"
}

printf "dns-check (%s) " "${host_under_test}"

if [ -z "${host_under_test}" ]; then
  exit 1
fi

check_if_dns_is_resolvable_using_google >> "${EXECUTION_CACHE_FILE}"

record_check_google_success_count=$(grep -E "${record_check_google}: 0" "${EXECUTION_CACHE_FILE}" | wc -l)
record_check_google_failure_count=$(grep -E "${record_check_google}: 1" "${EXECUTION_CACHE_FILE}" | wc -l)

printf "[google: ok=%s fail=%s] " "${record_check_google_success_count}" "${record_check_google_failure_count}"

check_if_dns_is_resolvable_locally >> "${EXECUTION_CACHE_FILE}"

record_check_local_success_count=$(grep -E "${record_check_local}: 0" "${EXECUTION_CACHE_FILE}" | wc -l)
record_check_local_failure_count=$(grep -E "${record_check_local}: 1" "${EXECUTION_CACHE_FILE}" | wc -l)

printf "[local: ok=%s fail=%s] " "${record_check_local_success_count}" "${record_check_local_failure_count}"

echo ""

if [ "${record_check_google_success_count}" -gt 2 ] && \
   [ "${record_check_local_success_count}" -gt 2 ]; then
  exit 0
fi

exit 1
