#!/bin/bash
REGEX="${1}"
COUNT=${2-1}

CACHE_FILE=$(mktemp)

echo "cluster-issuers (Regex: \"${REGEX}\" ${COUNT})"
echo ""

kubectl get ClusterIssuer \
| egrep "NAME|${REGEX}|^ " \
| tee "${CACHE_FILE?}"

CLUSTER_ISSUERS_READY_COUNT=$(
egrep "${REGEX}.*True" "${CACHE_FILE?}" \
| wc -l
)

COUNT_TO_COMPARE=$((${COUNT} -1))

if [ "${CLUSTER_ISSUERS_READY_COUNT}" -gt ${COUNT_TO_COMPARE} ]; then
  exit 0
fi

exit 1
