#!/bin/bash
COUNT=${1-1}

CACHE_FILE=$(mktemp)

echo "external-secrets (${COUNT} External Secrets)"
echo ""

kubectl get ExternalSecret -A \
| tee "${CACHE_FILE?}"

EXTERNAL_SECRETS_SYNCED_COUNT=$(grep -E "SecretSynced.*True" "${CACHE_FILE?}" | wc -l)

COUNT_TO_COMPARE=$((${COUNT} -1))

if [ "${EXTERNAL_SECRETS_SYNCED_COUNT}" -gt ${COUNT_TO_COMPARE} ]; then
  exit 0
fi

exit 1
