#!/bin/bash
cache_file=$(mktemp)
trap 'rm -f "${cache_file}"' EXIT

echo "external-secrets (Valid Cluster Secret Store)"
echo ""

kubectl get ClusterSecretStore \
| tee "${cache_file?}"

grep \
  --quiet "Valid.*True" "${cache_file?}"

exit $?
