#!/bin/bash
CACHE_FILE=$(mktemp)

echo "external-secrets (Valid Cluster Secret Store)"
echo ""

kubectl get ClusterSecretStore \
| tee "${CACHE_FILE?}"

grep \
  --quiet "Valid.*True" "${CACHE_FILE?}"

exit $?
