#!/bin/bash
CACHE_FILE=$(mktemp)

echo "external-secrets (4 External Secrets)"
echo ""

kubectl get ExternalSecret -A \
| tee "${CACHE_FILE?}"

EXTERNAL_SECRETS_SYNCED_COUNT=$(grep -E "SecretSynced.*True" "${CACHE_FILE?}" | wc -l)

if [ "${EXTERNAL_SECRETS_SYNCED_COUNT}" -gt 3 ]; then
  exit 0
fi

exit 1
