#!/bin/bash
count="${1:-1}"

cache_file=$(mktemp)
trap 'rm -f "${cache_file}"' EXIT

echo "external-secrets (${count} External Secrets)"
echo ""

kubectl get ExternalSecret -A \
| tee "${cache_file?}"

external_secrets_synced_count=$(grep -E "SecretSynced.*True" "${cache_file?}" | wc -l)

count_to_compare=$((count - 1))

if [ "${external_secrets_synced_count}" -gt "${count_to_compare}" ]; then
  exit 0
fi

exit 1
