#!/bin/bash
export THIS_SCRIPT_DIRECTORY=$(dirname $0)
export PATH=${PATH}:${THIS_SCRIPT_DIRECTORY}

ENVIRONMENT_ID="$1"

if [ -z "${ENVIRONMENT_ID}" ]; then
  echo "Please inform Environment ID."
  exit 1
fi

export EXECUTION_CACHE_FILE=$(mktemp)

# Resource Group
while ! resource-groups "${ENVIRONMENT_ID?}"; do
  sleep 10; clear
done
echo ""

# AKS
while ! aks "${ENVIRONMENT_ID?}"; do
  sleep 30; clear
done
echo ""

# Namespaces
while ! namespaces; do
  sleep 10; clear
done
echo ""

# external-secrets ClusterSecretStore
while ! external-secrets-secret-store; do
  sleep 10; clear
done
echo ""

# external-secrets ExternalSecret
while ! external-secrets 1; do
  sleep 10; clear
done
echo ""

# argo-cd pods running
while ! argocd-pods-running 7; do
  sleep 20;
done
echo ""

# external-secrets ExternalSecret
while ! external-secrets 4; do
  sleep 10; clear
done
echo ""

# argo-cd DNS check
while ! check-dns "$(argocd-host)"; do
  sleep 15;
done
echo ""

# argo-cd Certificate check
while ! check-certificates "^argocd" 1; do
  sleep 15;
done
echo ""

# argo-cd curl check
while ! check-curl-wait "$(argocd-host)"; do
  sleep 15;
done
echo ""
