#!/bin/bash
kubectl -n istio-ingress get svc -l istio=ingress

echo ""

kubectl \
  --namespace istio-ingress \
  get ingress,certificates,secrets \
| grep -vE "^secret/default|^secret/.*token|^secret/sh.helm"

echo ""

kubectl -n istio-ingress logs -l istio=ingress --tail 5
