#!/bin/bash
CACHE_FILE=$(mktemp)

echo "Namespaces (cert-manager and external-secrets)"
echo ""

kubectl get namespaces \
| grep -vE "^default|^kube" \
| tee "${CACHE_FILE?}"

NAMESPACE_COUNT=$(grep -E "cert-manager|external-secrets" "${CACHE_FILE?}" | wc -l)

if [ "${NAMESPACE_COUNT}" -gt 1 ]; then
  exit 0
fi

exit 1
