#!/bin/bash
regex="${1?}"
count="${2:-1}"
cache_file=$(mktemp)
trap 'rm -f "${cache_file}"' EXIT

echo "Namespaces (Regex: \"${regex}\" ${count})"
echo ""

kubectl get namespaces \
| grep -vE "^default|^kube" \
| tee "${cache_file?}"

namespace_count=$(grep -E "${regex}" "${cache_file?}" | wc -l)

count_to_compare=$((count - 1))

if [ "${namespace_count}" -gt "${count_to_compare}" ]; then
  exit 0
fi

exit 1
