#!/bin/bash
REGEX="${1}"
COUNT=${2-1}
CACHE_FILE=$(mktemp)

echo "Namespaces (Regex: \"${REGEX}\" ${COUNT})"
echo ""

kubectl get namespaces \
| grep -vE "^default|^kube" \
| tee "${CACHE_FILE?}"

NAMESPACE_COUNT=$(egrep "${REGEX}" "${CACHE_FILE?}" | wc -l)

COUNT_TO_COMPARE=$((${COUNT} -1))

if [ "${NAMESPACE_COUNT}" -gt ${COUNT_TO_COMPARE} ]; then
  exit 0
fi

exit 1
