#!/bin/bash
EXPRESSION="$1"

CACHE_FILE=$(mktemp)

echo "Resource Groups [${EXPRESSION}]"
echo ""

az group list \
  --output table \
| grep -E "Name|^----|${EXPRESSION}" \
| tee "${CACHE_FILE?}"

grep \
  --quiet "${EXPRESSION}-nrg.*Succeeded" "${CACHE_FILE?}"

exit $?
