#!/bin/bash
expression="${1?}"

cache_file=$(mktemp)
trap 'rm -f "${cache_file}"' EXIT

echo "Resource Groups [${expression}]"
echo ""

az group list \
  --output table \
| grep -E "Name|^----|${expression}" \
| tee "${cache_file?}"

grep \
  --quiet "${expression}-nrg.*Succeeded" "${cache_file?}"

exit $?
