annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Updated ExternalDNS version to v0.13.1."
apiVersion: v2
appVersion: 0.13.1
description: ExternalDNS synchronizes exposed Kubernetes Services and Ingresses with
  DNS providers.
home: https://github.com/kubernetes-sigs/external-dns/
icon: https://github.com/kubernetes-sigs/external-dns/raw/master/img/external-dns.png
keywords:
- kubernetes
- externaldns
- external-dns
- dns
- service
- ingress
maintainers:
- email: steve.hipwell@gmail.com
  name: stevehipwell
name: external-dns
sources:
- https://github.com/kubernetes-sigs/external-dns/
type: application
version: 1.12.0
