---
apiVersion: v1
kind: Secret
metadata:
  name: azure-config-file
type: Opaque
stringData:
  azure-config-file.json: |
    {
      "tenantId": "{{ .Values.tenantId }}",
      "subscriptionId": "{{ .Values.subscriptionId }}",
      "resourceGroup": "{{ .Values.resourceGroup }}",
      "useManagedIdentityExtension": true
    }
