#!/bin/bash
export THIS_SCRIPT_DIRECTORY=$(dirname $0)
export PATH=${PATH}:${THIS_SCRIPT_DIRECTORY}

show_usage() {
  cat <<EOF

  ./aks-nodepool-decrease \\
    --cluster-name aks-cluster-example \\
    --resource-group aks-cluster-example \\
    --name user1 \\
    --min 1 \\
    --max 5

EOF
}

while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
case $1 in
  -h | --help )
    show_usage
    exit
    ;;

  -cn | --cluster-name )
    shift; AKS_CLUSTER_NAME=$1
    ;;

  -rg | --resource-group )
    shift; AKS_CLUSTER_RESOURCE_GROUP_NAME=$1
    ;;

  -n | --name )
    shift; AKS_CLUSTER_NODEPOOL_NAME=$1
    ;;

  -min | --min )
    shift; AKS_NODEPOOL_MIN_COUNT=$1
    ;;

  -max | --max )
    shift; AKS_NODEPOOL_MAX_COUNT=$1
    ;;
esac; shift; done

if [[ "$1" == '--' ]]; then shift; fi

DRY_RUN=${DRY_RUN-n}

if [ -z "${AKS_CLUSTER_NAME}"                ] || \
   [ -z "${AKS_CLUSTER_RESOURCE_GROUP_NAME}" ] || \
   [ -z "${AKS_CLUSTER_NODEPOOL_NAME}"       ]; then
  echo "You must use ALL parameters."
  show_usage
  exit 1
fi

az aks nodepool update \
  --update-cluster-autoscaler \
  --cluster-name "${AKS_CLUSTER_NAME}" \
  --resource-group "${AKS_CLUSTER_RESOURCE_GROUP_NAME}" \
  --name "${AKS_CLUSTER_NODEPOOL_NAME}" \
  --min-count ${AKS_NODEPOOL_MIN_COUNT} \
  --max-count ${AKS_NODEPOOL_MAX_COUNT} \
  --only-show-errors 1> /dev/null

NODEPOOL_UPDATE_RESULT=$?

if [ "${NODEPOOL_UPDATE_RESULT}" == "0" ]; then
  AKS_NODEPOOL_DECREASE_EXECUTED="y"
else
  AKS_NODEPOOL_DECREASE_EXECUTED="n"
fi

echo "export AKS_NODEPOOL_DECREASE_EXECUTED=${AKS_NODEPOOL_DECREASE_EXECUTED}"

exit ${NODEPOOL_UPDATE_RESULT}
