#!/bin/bash
export THIS_SCRIPT_DIRECTORY=$(dirname $0)
export PATH=${PATH}:${THIS_SCRIPT_DIRECTORY}

show_usage() {
  cat <<EOF

  ./aks-nodepool-increase \\
    --cluster-name wasp-359ded9s \\
    --resource-group wasp-359ded9s \\
    --nodepool-name-old user1 \\
    --nodepool-name-new user2 \\
    --hard-limit-min 3 \\
    --hard-limit-max 5

EOF
}

while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
case $1 in
  -h | --help )
    show_usage
    exit
    ;;
  -cn | --cluster-name )
    shift; AKS_CLUSTER_NAME=$1
    ;;
  -rg | --resource-group )
    shift; AKS_CLUSTER_RESOURCE_GROUP_NAME=$1
    ;;
  -old | --nodepool-name-old )
    shift; AKS_CLUSTER_NODEPOOL_NAME_OLD=$1
    ;;
  -new | --nodepool-name-new )
    shift; AKS_CLUSTER_NODEPOOL_NAME_NEW=$1
    ;;
  -min | --hard-limit-min )
    shift; HARD_LIMIT_MIN=$1
    ;;
  -max | --hard-limit-max )
    shift; HARD_LIMIT_MAX=$1
    ;;
esac; shift; done

if [[ "$1" == '--' ]]; then shift; fi

if [ -z "${AKS_CLUSTER_NAME}"     ] || \
   [ -z "${AKS_CLUSTER_RESOURCE_GROUP_NAME}" ] || \
   [ -z "${AKS_CLUSTER_NODEPOOL_NAME_OLD}" ] || \
   [ -z "${AKS_CLUSTER_NODEPOOL_NAME_NEW}" ] || \
   [ -z "${HARD_LIMIT_MIN}" ] || \
   [ -z "${HARD_LIMIT_MAX}" ]; then
  echo "You must use ALL parameters."
  echo ""
  show_usage
  exit 1
fi

eval $(
  aks-nodepool-info \
    --cluster-name ${AKS_CLUSTER_NAME} \
    --resource-group ${AKS_CLUSTER_RESOURCE_GROUP_NAME} \
    --name ${AKS_CLUSTER_NODEPOOL_NAME_OLD}
)

export TOTAL_MAX=${AKS_NODEPOOL_MAX_COUNT}
export TOTAL_MIN=${AKS_NODEPOOL_MIN_COUNT}

eval $(
  aks-nodepool-info \
    --cluster-name ${AKS_CLUSTER_NAME} \
    --resource-group ${AKS_CLUSTER_RESOURCE_GROUP_NAME} \
    --name ${AKS_CLUSTER_NODEPOOL_NAME_NEW}
)

export TOTAL_MIN=$((${TOTAL_MIN} + ${AKS_NODEPOOL_MIN_COUNT}))
export TOTAL_MAX=$((${TOTAL_MAX} + ${AKS_NODEPOOL_MAX_COUNT}))

export AKS_NODEPOOL_MIN_COUNT_INCREASE=$((${HARD_LIMIT_MIN} - ${TOTAL_MIN}))
export AKS_NODEPOOL_MAX_COUNT_INCREASE=$((${HARD_LIMIT_MAX} - ${TOTAL_MAX}))

if [ "${AKS_NODEPOOL_MIN_COUNT_INCREASE}" -gt 0 ] || \
   [ "${AKS_NODEPOOL_MAX_COUNT_INCREASE}" -gt 0 ]; then
  export AKS_NODEPOOL_MIN_COUNT_UPDATE=$((${AKS_NODEPOOL_MIN_COUNT} + ${AKS_NODEPOOL_MIN_COUNT_INCREASE}))
  export AKS_NODEPOOL_MAX_COUNT_UPDATE=$((${AKS_NODEPOOL_MAX_COUNT} + ${AKS_NODEPOOL_MAX_COUNT_INCREASE}))

  echo "AKS_NODEPOOL_NAME......: ${AKS_CLUSTER_NODEPOOL_NAME_NEW}"
  echo "AKS_NODEPOOL_MIN_COUNT.: ${AKS_NODEPOOL_MIN_COUNT} + ${AKS_NODEPOOL_MIN_COUNT_INCREASE} = ${AKS_NODEPOOL_MIN_COUNT_UPDATE}"
  echo "AKS_NODEPOOL_MAX_COUNT.: ${AKS_NODEPOOL_MAX_COUNT} + ${AKS_NODEPOOL_MAX_COUNT_INCREASE} = ${AKS_NODEPOOL_MAX_COUNT_UPDATE}"

  az aks nodepool update \
    --name "${AKS_CLUSTER_NODEPOOL_NAME_NEW}" \
    --cluster-name "${AKS_CLUSTER_NAME}" \
    --resource-group "${AKS_CLUSTER_RESOURCE_GROUP_NAME}" \
    --update-cluster-autoscaler \
    --min-count ${AKS_NODEPOOL_MIN_COUNT_UPDATE} \
    --max-count ${AKS_NODEPOOL_MAX_COUNT_UPDATE} \
    --only-show-errors &> /dev/null
fi
