#!/bin/bash
show_usage() {
  cat <<EOF

  ./aks-nodepool-drain aks-user1-69591119-vmss000000

EOF
}

AKS_NODE_NAME=$1

if [ -z "${AKS_NODE_NAME}" ]; then
  echo "You must inform Node Name."
  show_usage
  exit 1
fi

kubectl drain \
  ${AKS_NODE_NAME?} \
  --ignore-daemonsets \
  --delete-emptydir-data \
  --force
