#!/bin/bash
export THIS_SCRIPT_DIRECTORY=$(dirname $0)
export PATH=${PATH}:${THIS_SCRIPT_DIRECTORY}

show_usage() {
  cat <<EOF

  ./aks-nodepool-increase \\
    --cluster-name aks-cluster-example \\
    --resource-group aks-cluster-example \\
    --source user1 \\
    --target user2 \\
    --hard-limit-min 3 \\
    --hard-limit-max 5 \\
    --dry-run

EOF
}

while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
case $1 in
  -h | --help )
    show_usage
    exit
    ;;
  -cn | --cluster-name )
    shift; AKS_CLUSTER_NAME=$1
    ;;
  -rg | --resource-group )
    shift; AKS_CLUSTER_RESOURCE_GROUP_NAME=$1
    ;;
  -s | --source )
    shift; AKS_CLUSTER_NODEPOOL_NAME_SOURCE=$1
    ;;
  -t | --target )
    shift; AKS_CLUSTER_NODEPOOL_NAME_TARGET=$1
    ;;
  -min | --hard-limit-min )
    shift; HARD_LIMIT_MIN=$1
    ;;
  -max | --hard-limit-max )
    shift; HARD_LIMIT_MAX=$1
    ;;
  --dry-run )
    shift; DRY_RUN="y"
    ;;
esac; shift; done

if [[ "$1" == '--' ]]; then shift; fi

DRY_RUN=${DRY_RUN-n}

if [ -z "${AKS_CLUSTER_NAME}"                 ] || \
   [ -z "${AKS_CLUSTER_RESOURCE_GROUP_NAME}"  ] || \
   [ -z "${AKS_CLUSTER_NODEPOOL_NAME_SOURCE}" ] || \
   [ -z "${AKS_CLUSTER_NODEPOOL_NAME_TARGET}" ] || \
   [ -z "${HARD_LIMIT_MIN}"                   ] || \
   [ -z "${HARD_LIMIT_MAX}"                   ]; then
  echo "You must use ALL parameters."
  echo ""
  show_usage
  exit 1
fi

eval $(
  aks-nodepool-info \
    --cluster-name ${AKS_CLUSTER_NAME} \
    --resource-group ${AKS_CLUSTER_RESOURCE_GROUP_NAME} \
    --name ${AKS_CLUSTER_NODEPOOL_NAME_SOURCE}
)

export TOTAL_MIN=${AKS_NODEPOOL_MIN_COUNT}
export TOTAL_MAX=${AKS_NODEPOOL_MAX_COUNT}

eval $(
  aks-nodepool-info \
    --cluster-name ${AKS_CLUSTER_NAME} \
    --resource-group ${AKS_CLUSTER_RESOURCE_GROUP_NAME} \
    --name ${AKS_CLUSTER_NODEPOOL_NAME_TARGET}
)

export TOTAL_MIN=$((${TOTAL_MIN} + ${AKS_NODEPOOL_MIN_COUNT}))
export TOTAL_MAX=$((${TOTAL_MAX} + ${AKS_NODEPOOL_MAX_COUNT}))

export AKS_NODEPOOL_MIN_COUNT_INCREASE=$((${HARD_LIMIT_MIN} - ${TOTAL_MIN}))
export AKS_NODEPOOL_MAX_COUNT_INCREASE=$((${HARD_LIMIT_MAX} - ${TOTAL_MAX}))

if [ "${AKS_NODEPOOL_MIN_COUNT_INCREASE}" -gt 0 ] || \
   [ "${AKS_NODEPOOL_MAX_COUNT_INCREASE}" -gt 0 ]; then
  export AKS_NODEPOOL_MIN_COUNT_UPDATE=$((${AKS_NODEPOOL_MIN_COUNT} + ${AKS_NODEPOOL_MIN_COUNT_INCREASE}))
  export AKS_NODEPOOL_MAX_COUNT_UPDATE=$((${AKS_NODEPOOL_MAX_COUNT} + ${AKS_NODEPOOL_MAX_COUNT_INCREASE}))

  echo "[${AKS_CLUSTER_NODEPOOL_NAME_TARGET}] MIN=${AKS_NODEPOOL_MIN_COUNT} -> ${AKS_NODEPOOL_MIN_COUNT_UPDATE} MAX=${AKS_NODEPOOL_MAX_COUNT} -> ${AKS_NODEPOOL_MAX_COUNT_UPDATE}"

  if [ "${DRY_RUN}" == "n" ]; then
    az aks nodepool update \
      --name "${AKS_CLUSTER_NODEPOOL_NAME_TARGET}" \
      --cluster-name "${AKS_CLUSTER_NAME}" \
      --resource-group "${AKS_CLUSTER_RESOURCE_GROUP_NAME}" \
      --update-cluster-autoscaler \
      --min-count ${AKS_NODEPOOL_MIN_COUNT_UPDATE} \
      --max-count ${AKS_NODEPOOL_MAX_COUNT_UPDATE} \
      --only-show-errors &> /dev/null
  fi
fi
