#!/bin/bash
export THIS_SCRIPT_DIRECTORY=$(dirname $0)
export PATH=${PATH}:${THIS_SCRIPT_DIRECTORY}
export EXECUTION_ID="$(date +"%Y-%m-%d_%H-%M-%S")_$(uuidgen)"
export CACHE_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/.cache/${EXECUTION_ID}"
export ALL_PODS_FILE="${THIS_SCRIPT_DIRECTORY}/all-pods.txt"
export ALL_REPLICASETS_FILE="${THIS_SCRIPT_DIRECTORY}/all-replicasets.txt"

mkdir -p "${CACHE_DIRECTORY}"

show_usage() {
  cat <<EOF

  ./aks-node-rollout-restart \\
    --cluster-name aks-cluster-example \\
    --resource-group aks-cluster-example \\
    --name aks-system1-37832835-vmss000000 \\
    --dry-run

EOF
}

while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
case $1 in
  -h | --help )
    show_usage
    exit
    ;;
  -cn | --cluster-name )
    shift; AKS_CLUSTER_NAME=$1
    ;;
  -rg | --resource-group )
    shift; AKS_CLUSTER_RESOURCE_GROUP_NAME=$1
    ;;
  -n | --name )
    shift; AKS_NODE_NAME=$1
    ;;
  -c | --count )
    shift; AKS_NODE_COUNT=$1
    ;;
  -d | --debug )
    shift; DEBUG_LEVEL=$1
    ;;
  --dry-run )
    shift; DRY_RUN="y"
    ;;
esac; shift; done

if [[ "$1" == '--' ]]; then shift; fi

DRY_RUN=${DRY_RUN-n}
DEBUG_LEVEL=${DEBUG_LEVEL-1}
AKS_NODE_COUNT=${AKS_NODE_COUNT-0}

if [ -z "${AKS_CLUSTER_NAME}"                ] || \
   [ -z "${AKS_CLUSTER_RESOURCE_GROUP_NAME}" ] || \
   [ -z "${AKS_NODE_NAME}${AKS_NODE_COUNT}"  ]; then
  show_usage
  exit 1
fi

if ! which kubectl &> /dev/null; then
  az aks install-cli
fi

KUBECTL_CONFIG_CONTEXT_EXISTS=$(kubectl config get-contexts | grep ${AKS_CLUSTER_NAME} | wc -l)

if [ "${KUBECTL_CONFIG_CONTEXT_EXISTS}" == "0" ]; then
  az aks get-credentials \
    --name ${AKS_CLUSTER_NAME?} \
    --resource-group ${AKS_CLUSTER_RESOURCE_GROUP_NAME?} \
    --overwrite-existing \
    --admin
fi

log() {
  MESSAGE="$1"

  echo "$(date +"%Y-%m-%d %H:%M:%S") ${MESSAGE}"
}

deployment_file() {
  DEPLOYMENT_NAMESPACE=$1
  DEPLOYMENT_NAME=$2

  mkdir -p "${CACHE_DIRECTORY}/${DEPLOYMENT_NAMESPACE}"

  FILE_NAME="${CACHE_DIRECTORY}/${DEPLOYMENT_NAMESPACE}/${DEPLOYMENT_NAME}"

  echo "${FILE_NAME}"
}

get_all_replicasets() {
  kubectl get replicasets \
    --all-namespaces \
    --output jsonpath='{range .items[*]}{.metadata.namespace} {.metadata.name} {.metadata.ownerReferences[0].kind} {.metadata.ownerReferences[0].name}{"\n"}{end}' > "${ALL_REPLICASETS_FILE?}"
}

get_all_pods() {
  kubectl get pods \
    --all-namespaces \
    --output jsonpath='{range .items[*]}{.spec.nodeName} {.metadata.namespace} {.metadata.name} {.metadata.ownerReferences[0].kind} {.metadata.ownerReferences[0].name}{"\n"}{end}' > "${ALL_PODS_FILE?}"

  grep ReplicaSet "${ALL_PODS_FILE?}"
}

get_deployment_name() {
  REPLICASET_NAMESPACE=$1
  REPLICASET_NAME=$2

  grep "${REPLICASET_NAMESPACE?} ${REPLICASET_NAME?} Deployment" "${ALL_REPLICASETS_FILE?}" \
  | awk '{ print $4 }'
}

node_cordon() {
  NODE_NAME=$1

  if [ "${DRY_RUN}" != "y" ]; then
    kubectl cordon ${NODE_NAME?}
  else
    log "[${NODE_NAME?}] cordoned"
  fi
}

node_list() {
  NODE_NAME=$1

  kubectl get nodes \
    --output jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' \
    --selector '!rollout-restarted' \
  | grep -E "${NODE_NAME}"
}

rollout_restart_deployments() {
  NODE_NAME=$1

  if [ "${DEBUG_LEVEL}" -gt "2" ]; then
    log "[NODE_NAME=${NODE_NAME?}] [CACHE_DIRECTORY=${CACHE_DIRECTORY}]"
  fi

  grep -rl "${NODE_NAME?}" "${CACHE_DIRECTORY}" \
  | while read -r FILENAME; do
    LINE="${FILENAME#$CACHE_DIRECTORY/}"
    DEPLOYMENT_DIRECTORY=$(dirname "${FILENAME}")
    DEPLOYMENT_NAMESPACE=$(awk -F '/' '{ print $1 }' <<< "${LINE}")
    DEPLOYMENT_NAME=$(     awk -F '/' '{ print $2 }' <<< "${LINE}")
    DEPLOYMENT_MARK="${DEPLOYMENT_DIRECTORY?}/${DEPLOYMENT_NAME?}.rollout"

    if [ "${DEBUG_LEVEL}" -gt "2" ]; then
      log "[FILENAME=${FILENAME}]"
      log "[LINE=${LINE}]"
      log "DEPLOYMENT_DIRECTORY.: ${DEPLOYMENT_DIRECTORY}"
      log "DEPLOYMENT_NAMESPACE.: ${DEPLOYMENT_NAMESPACE}"
      log "DEPLOYMENT_NAME......: ${DEPLOYMENT_NAME}"
      log "DEPLOYMENT_MARK......: ${DEPLOYMENT_MARK}"
    fi

    if ! [ -e "${DEPLOYMENT_MARK}" ]; then
      echo "${NODE_NAME?}" $(date +"%Y-%m-%d %H:%M:%S") > "${DEPLOYMENT_MARK}"

      log "[${NODE_NAME?}] [${DEPLOYMENT_NAMESPACE?}] rollout restart deployment ${DEPLOYMENT_NAME?}"

      if [ "${DRY_RUN}" != "y" ]; then
        kubectl \
          --namespace ${DEPLOYMENT_NAMESPACE?} \
          rollout restart deployment ${DEPLOYMENT_NAME?} > /dev/null
      fi
    fi
  done

  kubectl label node ${NODE_NAME?} rollout-restarted=true 1> /dev/null
}

log "Collecting all ReplicaSets data..."

get_all_replicasets

log "Collecting all Pods/Deployments data..."

get_all_pods | while read LINE; do
  POD_NODE_NAME=$(awk '{ print $1 }' <<< "${LINE}")
  POD_NAMESPACE=$(awk '{ print $2 }' <<< "${LINE}")
  POD_NAME=$(     awk '{ print $3 }' <<< "${LINE}")
  POD_OWNER=$(    awk '{ print $5 }' <<< "${LINE}")

  REPLICASET_DEPLOYMENT_NAME="$(get_deployment_name "${POD_NAMESPACE}" "${POD_OWNER}")"

  if [ "${DEBUG_LEVEL}" == "1" ]; then
    log "[${POD_NODE_NAME}] [${POD_NAMESPACE}] ${POD_OWNER} ${POD_NAME}"
  else
    if [ "${DEBUG_LEVEL}" -gt "1" ]; then
      log "[${POD_NODE_NAME}] [${POD_NAMESPACE}] ${POD_OWNER} ${POD_NAME} [${REPLICASET_DEPLOYMENT_NAME}]"
    else
      if [ "${DEBUG_LEVEL}" -gt "2" ]; then
        log "[${LINE}]"
      fi
    fi
  fi

  if [ -n "${REPLICASET_DEPLOYMENT_NAME}" ]; then
    FILE_NAME=$(deployment_file "${POD_NAMESPACE}" "${REPLICASET_DEPLOYMENT_NAME}")

    echo "${POD_NODE_NAME?} ${POD_NAME?}" >> "${FILE_NAME}"
  fi
done

log ""
log "Initiating Deployments Rollout Restart..."
log ""

if [ "${AKS_NODE_COUNT}" == "0" ]; then
  NODE_LIST_NAMES=$(node_list "${AKS_NODE_NAME}")
else
  NODE_LIST_NAMES=$(node_list "${AKS_NODE_NAME}" | head -${AKS_NODE_COUNT})
fi

while read NODE_NAME; do
  node_cordon "${NODE_NAME}"
done <<< "${NODE_LIST_NAMES}"

while read NODE_NAME; do
  rollout_restart_deployments ${NODE_NAME?}
done <<< "${NODE_LIST_NAMES}"

log ""
log "Finish"
