#!/bin/bash
export THIS_SCRIPT_DIRECTORY=$(dirname $0)
export PATH=${PATH}:${THIS_SCRIPT_DIRECTORY}

CACHE_FILE=$(mktemp)

LINE=$(
  az aks list \
    --output table \
| sed 1,2d \
| awk '{ print $1, $3, $4, $2 }' \
| column --table \
| fzf
)

AKS_CLUSTER_NAME=$(awk '{ print $1 }' <<< "${LINE}")
AKS_CLUSTER_RESOURCE_GROUP_NAME=$(awk '{ print $2 }' <<< "${LINE}")
AKS_CLUSTER_KUBERNETES_VERSION=$(awk '{ print $3 }' <<< "${LINE}")
AKS_CLUSTER_LOCATION=$(awk '{ print $4 }' <<< "${LINE}")

AKS_CLUSTER_KUBERNETES_VERSION=$(aks-versions "${AKS_CLUSTER_KUBERNETES_VERSION}" "${AKS_CLUSTER_LOCATION}" | fzf)

az aks nodepool list \
  --cluster-name ${AKS_CLUSTER_NAME} \
  --resource-group ${AKS_CLUSTER_RESOURCE_GROUP_NAME} \
  --output tsv \
  --query '[*].name' > ${CACHE_FILE}

NODEPOOL_COUNT=$(cat ${CACHE_FILE} | wc -l)

if [ "${NODEPOOL_COUNT}" -eq 1 ]; then
  NODEPOOL_NAME="$(cat ${CACHE_FILE})"
else
  NODEPOOL_NAME="$(cat ${CACHE_FILE} | fzf)"
fi

nodepool_vm_sizes() {
  cat <<EOF
Standard_D16s_v3
Standard_D32s_v3
EOF
}

NODEPOOL_VM_SIZE="$(nodepool_vm_sizes | fzf)"

NODEPOOL_MODE=$(az aks nodepool show \
  --cluster-name ${AKS_CLUSTER_NAME} \
  --resource-group ${AKS_CLUSTER_RESOURCE_GROUP_NAME} \
  --name ${NODEPOOL_NAME} \
  --output tsv \
  --query 'mode')

cat <<EOF

  ./aks-nodepool-creation \\
    --cluster-name ${AKS_CLUSTER_NAME} \\
    --resource-group ${AKS_CLUSTER_RESOURCE_GROUP_NAME} \\
    --source ${NODEPOOL_NAME} \\
    --name user1 \\
    --vm-size ${NODEPOOL_VM_SIZE} \\
    --mode ${NODEPOOL_MODE} \\
    --kubernetes-version ${AKS_CLUSTER_KUBERNETES_VERSION} \\
    --min 0 \\
    --max 0 \\
    --dry-run

EOF
