#!/bin/bash
export THIS_SCRIPT_DIRECTORY=$(dirname $0)
export PATH=${PATH}:${THIS_SCRIPT_DIRECTORY}

show_usage() {
  cat <<EOF

  ./aks-nodepool-show \\
    --cluster-name aks-cluster-example \\
    --resource-group aks-cluster-example

  ./aks-nodepool-show \\
    --subscription 70d05914-4c56-47be-a78c-3b1a47b8f820 \\
    --cluster-name aks-cluster-example \\
    --resource-group aks-cluster-example

EOF
}

while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
case $1 in
  -h | --help )
    show_usage
    exit
    ;;

  -s | --subscription )
    shift; AZURE_SUBSCRIPTION=$1
    ;;

  -cn | --cluster-name )
    shift; AKS_CLUSTER_NAME=$1
    ;;

  -rg | --resource-group )
    shift; AKS_CLUSTER_RESOURCE_GROUP_NAME=$1
    ;;

  -n | --name )
    shift; AKS_NODEPOOL_NAME=$1
    ;;
esac; shift; done

if [[ "$1" == '--' ]]; then shift; fi

DRY_RUN=${DRY_RUN-n}

if [ -z "${AZURE_SUBSCRIPTION}" ]; then
  AZURE_SUBSCRIPTION=$(az account show \
    --query id \
    --output tsv)
fi

if [ -z "${AKS_CLUSTER_NAME}"                ] || \
   [ -z "${AKS_CLUSTER_RESOURCE_GROUP_NAME}" ]; then
  show_usage
  exit 1
fi

get_nodepool_list() {
  az aks nodepool list \
    --subscription "${AZURE_SUBSCRIPTION}" \
    --cluster-name ${AKS_CLUSTER_NAME?} \
    --resource-group ${AKS_CLUSTER_RESOURCE_GROUP_NAME?} \
    --output tsv \
    --query '[].name' \
  | egrep "${AKS_NODEPOOL_NAME}"
}

(
  HEADER_LINE_1="Name         Min     Max     Count   Space   MaxPods   Version   Mode     NodeSize            ProvisioningState  AutoScale  Zones  Subnet          CIDR              "
  HEADER_LINE_2="-----------  ------  ------  ------  ------  --------  --------  -------  ------------------  ------------------ ---------- ------ --------------- ----------------- "
  
  echo "${HEADER_LINE_1?}"
  echo "${HEADER_LINE_2?}"

  TOTAL_MIN=0
  TOTAL_MAX=0
  TOTAL_COUNT=0
  TOTAL_SPACE=0

  while read NODEPOOL_NAME; do
    unset AKS_NODEPOOL_MIN_COUNT
    unset AKS_NODEPOOL_MAX_COUNT
    unset AKS_NODEPOOL_COUNT
    unset AKS_NODEPOOL_MAX_PODS
    unset AKS_NODEPOOL_ORCHESTRATOR_VERSION
    unset AKS_NODEPOOL_VM_SIZE
    unset AKS_NODEPOOL_MODE
    unset AKS_NODEPOOL_ENABLE_AUTO_SCALING
    unset AKS_NODEPOOL_AVAILABILITY_ZONES

    eval $(
      aks-nodepool-info \
        --subscription "${AZURE_SUBSCRIPTION}" \
        --cluster-name ${AKS_CLUSTER_NAME?} \
        --resource-group ${AKS_CLUSTER_RESOURCE_GROUP_NAME?} \
        --name ${NODEPOOL_NAME?}
    )

    if [ "${AKS_NODEPOOL_MIN_COUNT}" == "null" ]; then
      export AKS_NODEPOOL_MIN_COUNT="0"
    fi

    if [ "${AKS_NODEPOOL_MAX_COUNT}" == "null" ]; then
      export AKS_NODEPOOL_MAX_COUNT="0"
    fi

    if [ "${AKS_NODEPOOL_AVAILABILITY_ZONES}" == "null" ]; then
      export AKS_NODEPOOL_AVAILABILITY_ZONES="-"
    else
      export AKS_NODEPOOL_AVAILABILITY_ZONES=$(
        jq .[] -r <<< "${AKS_NODEPOOL_AVAILABILITY_ZONES}" \
        | sort \
        | tr "\n" "," \
        | sed 's/.$//'
      )
    fi

    AKS_NODEPOOL_SPACE_COUNT=$((${AKS_NODEPOOL_MAX_COUNT-0} - ${AKS_NODEPOOL_COUNT-0}))

    if [ "${AKS_NODEPOOL_SPACE_COUNT}" -lt 0 ]; then
      AKS_NODEPOOL_SPACE_COUNT=0
    fi

    AKS_NODEPOOL_VNET_SUBNET_CIDR=$(az network vnet subnet show \
      --ids ${AKS_NODEPOOL_VNET_SUBNET_ID} \
      --query 'addressPrefix' \
      --output tsv)

    printf "%s " ${NODEPOOL_NAME}
    printf "%s " ${AKS_NODEPOOL_MIN_COUNT}
    printf "%s " ${AKS_NODEPOOL_MAX_COUNT}
    printf "%s " ${AKS_NODEPOOL_COUNT}
    printf "%s " ${AKS_NODEPOOL_SPACE_COUNT}
    printf "%s " ${AKS_NODEPOOL_MAX_PODS}
    printf "%s " ${AKS_NODEPOOL_ORCHESTRATOR_VERSION}
    printf "%s " ${AKS_NODEPOOL_MODE}
    printf "%s " ${AKS_NODEPOOL_VM_SIZE}
    printf "%s " ${AKS_NODEPOOL_PROVISIONING_STATE}
    printf "%s " ${AKS_NODEPOOL_ENABLE_AUTO_SCALING}
    printf "%s " ${AKS_NODEPOOL_AVAILABILITY_ZONES}
    printf "%s " ${AKS_NODEPOOL_VNET_SUBNET_ID##*/}
    printf "%s " ${AKS_NODEPOOL_VNET_SUBNET_CIDR}
    
    echo ""

    TOTAL_MIN=$((${TOTAL_MIN} + ${AKS_NODEPOOL_MIN_COUNT-0}))
    TOTAL_MAX=$((${TOTAL_MAX} + ${AKS_NODEPOOL_MAX_COUNT-0}))
    TOTAL_COUNT=$((${TOTAL_COUNT} + ${AKS_NODEPOOL_COUNT-0}))
    TOTAL_SPACE=$((${TOTAL_SPACE} + ${AKS_NODEPOOL_SPACE_COUNT-0}))
  done <<< "$(get_nodepool_list)"

  echo "${HEADER_LINE_2?}"
  echo "Total ${TOTAL_MIN} ${TOTAL_MAX} ${TOTAL_COUNT} ${TOTAL_SPACE}"
) \
| column -t
