#!/bin/bash
show_usage() {
  cat <<EOF

  ./aks-nodepool-decrease-calc \\
    --count 3 \\
    --min 3 \\
    --max 5

  ./aks-nodepool-decrease-calc \\
    --mode System \\
    --count 3 \\
    --min 3 \\
    --max 5

EOF
}

while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
case $1 in
  -h | --help )
    show_usage
    exit
    ;;

  -m | --mode )
    shift; NODEPOOL_MODE=$1
    ;;

  -c | --count )
    shift; NODEPOOL_COUNT=$1
    ;;

  -mi | --min )
    shift; NODEPOOL_MIN_COUNT=$1
    ;;

  -mx | --max )
    shift; NODEPOOL_MAX_COUNT=$1
    ;;
esac; shift; done

if [[ "$1" == '--' ]]; then shift; fi

if [ -z "${NODEPOOL_COUNT}"     ] || \
   [ -z "${NODEPOOL_MIN_COUNT}" ] || \
   [ -z "${NODEPOOL_MAX_COUNT}" ]; then
  echo "You must use ALL parameters."
  show_usage
  exit 1
fi

NODEPOOL_MODE=${NODEPOOL_MODE-User}

CURRENT_RANGE=$((${NODEPOOL_MAX_COUNT} - ${NODEPOOL_MIN_COUNT}))

DIFFERENCE=$((${NODEPOOL_MAX_COUNT} - ${NODEPOOL_COUNT}))

if [ "${CURRENT_RANGE}" -gt 0 ] && \
   [ "${DIFFERENCE}"    -gt 0 ]; then
  NEW_MIN_COUNT=$((${NODEPOOL_COUNT} - ${CURRENT_RANGE}))
  NEW_MAX_COUNT=$((${NODEPOOL_COUNT}))

  if [ "${NEW_MIN_COUNT}" -lt 1 ] && [ "${NODEPOOL_MODE?}" == "System" ]; then
    NEW_MIN_COUNT=1
  fi

  if [ "${NEW_MIN_COUNT}" -lt 0 ]; then
    NEW_MIN_COUNT=0
  fi

  echo "export AKS_NODEPOOL_DECREASE=y"
  echo "export AKS_NODEPOOL_DECREASE_MIN_COUNT=${NEW_MIN_COUNT}"
  echo "export AKS_NODEPOOL_DECREASE_MAX_COUNT=${NEW_MAX_COUNT}"
  echo "export AKS_NODEPOOL_DECREASE_DIFFERENCE=${DIFFERENCE}"
  echo "export AKS_NODEPOOL_DECREASE_CURRENT_RANGE=${CURRENT_RANGE}"
else
  echo "export AKS_NODEPOOL_DECREASE=n"
fi
