---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-wildcard
spec:
  commonName: "*.{{ $.Values.dns.cname }}.{{ $.Values.dns.domain }}"

  dnsNames:
    - "*.{{ $.Values.dns.cname }}.{{ $.Values.dns.domain }}"

  secretName: {{ $.Values.secret.prefix }}wildcard

  issuerRef:
    kind: ClusterIssuer
    name: {{ $.Values.certificate.type }}-{{ $.Values.certificate.server }}-istio
