---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-gateway
spec:
  commonName: gateway.{{ $.Values.dns.cname }}.{{ $.Values.dns.domain }}
  
  dnsNames:
    - gateway.{{ $.Values.dns.cname }}.{{ $.Values.dns.domain }}

  secretName: {{ $.Values.secret.prefix }}gateway

  issuerRef:
    kind: ClusterIssuer
    name: {{ $.Values.certificate.type }}-{{ $.Values.certificate.server }}-istio

{{- range $cname := .Values.certificate.list }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-{{ $cname }}
spec:
  commonName: {{ $cname }}.{{ $.Values.dns.cname }}.{{ $.Values.dns.domain }}
  
  dnsNames:
    - {{ $cname }}.{{ $.Values.dns.cname }}.{{ $.Values.dns.domain }}

  secretName: {{ $.Values.secret.prefix }}{{ $cname }}

  issuerRef:
    kind: ClusterIssuer
    name: {{ $.Values.certificate.type }}-{{ $.Values.certificate.server }}-istio
{{- end }}
