---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: public-ingress-gateway
spec:
  selector:
    istio: ingress

  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "gateway.{{ $.Values.dns.cname }}.{{ $.Values.dns.domain }}"
      tls:
        httpsRedirect: false # The HTTPS redirections will be handled in the VirtualService layer to not conflict with certificates renewing.

    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "gateway.{{ $.Values.dns.cname }}.{{ $.Values.dns.domain }}"
      tls:
        mode: SIMPLE
        credentialName: {{ $.Values.secret.prefix }}gateway

{{- range $cname := .Values.certificate.list }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: public-ingress-{{ $cname }}
spec:
  selector:
    istio: ingress

  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "{{ $cname }}.{{ $.Values.dns.cname }}.{{ $.Values.dns.domain }}"
      tls:
        httpsRedirect: false # The HTTPS redirections will be handled in the VirtualService layer to not conflict with certificates renewing.

    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "{{ $cname }}.{{ $.Values.dns.cname }}.{{ $.Values.dns.domain }}"
      tls:
        mode: SIMPLE
        credentialName: {{ $.Values.secret.prefix }}{{ $cname }}
{{- end }}
