{{- range $cname := .Values.certificate.list }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ $cname }}
  annotations:
    external-dns.alpha.kubernetes.io/target: gateway.{{ $.Values.dns.cname }}.{{ $.Values.dns.domain }}
spec:
  ingressClassName: istio

  rules:
    - host: {{ $cname }}.{{ $.Values.dns.cname }}.{{ $.Values.dns.domain }}
      http:
        paths:
          - path: /.well-known/not-used-path/
            pathType: Prefix
            backend:
              service: 
                name: non-existent-service
                port:
                  number: 80
{{- end }}
