---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-virtual-service-public
spec:
  hosts:
    - argocd.{{ $.Values.dns.cname }}.{{ $.Values.dns.domain }}

  gateways:
    - public-ingress-argocd

  http:
    - name: argocd
      headers:
        request:
          add:
            X-A1-origin-1: public-ingress-argocd

      route:
        - destination:
            host: argocd-server.argocd.svc.cluster.local
            port:
              number: 80
