---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-virtual-service-public
spec:
  hosts:
    - argocd.{{ $.Values.dns.cname }}.{{ $.Values.dns.domain }}

  gateways:
    - public-ingress-argocd

  http:
    - match:
        - scheme:
            exact: http
          uri:
            regex: "^/(([^\\.].*)|(\\.[^w].*)|(\\.w[^e].*)|(\\.we[^l].*)|(\\.wel[^l].*)|(\\.well[^\\-].*))"
      redirect:
        scheme: https
        redirectCode: 302 # 302 to not mess with risky permanent redirections since a workaround

    - name: argocd
      headers:
        request:
          add:
            X-A1-origin-1: public-ingress-argocd

      route:
        - destination:
            host: argocd-server.argocd.svc.cluster.local
            port:
              number: 80
