argo-cd:
  server:
    ingress:
      enabled: true
      https: true
      hosts:
        - ${server_ingress_host}
      pathType: ImplementationSpecific
      paths:
        - /
      tls:
        - secretName: argocd-ingress
          hosts:
            - ${server_ingress_host}
      annotations:
        cert-manager.io/cluster-issuer: ${server_ingress_issuer_name}
        external-dns.alpha.kubernetes.io/ttl: "1m"
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
