environment:
  id: undefined-id
  domain: sandbox.wasp.silvios.me
  cluster: undefined-cluster-name

helm:
  files:
    - values-aks.yaml

project: infra

source:
  repoURL: git@github.com:smsilva/wasp-gitops.git
  path: infrastructure/bootstrap/applications
  targetRevision: development

destination:
  name: in-cluster
