environment:
  id: undefined-id
  domain: sandbox.wasp.silvios.me
  cluster:
    name: undefined-cluster-name
    ingress:
      type: nginx
    certificates:
      type: letsencrypt
      server: staging

helm:
  files:
    - values-aks.yaml

project: infra

source:
  repoURL: git@github.com:smsilva/wasp-gitops.git
  path: infrastructure/charts/applications
  targetRevision: dev

destination:
  name: in-cluster
