---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      tenantId: {{ .Values.clusterSecretStore.armTenantId }}
      vaultUrl: https://{{ .Values.clusterSecretStore.keyVaultName }}.vault.azure.net

      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
