---
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
spec:
  provider:
    azurekv:
      tenantId: {{ .Values.clusterSecretStore.armTenantId }}
      vaultUrl: https://{{ .Values.clusterSecretStore.keyVaultName }}.vault.azure.net

      authSecretRef:
        clientId:
          key: ARM_CLIENT_ID
          name: azurerm-service-principal
          namespace: external-secrets

        clientSecret:
          key: ARM_CLIENT_SECRET
          name: azurerm-service-principal
          namespace: external-secrets
