---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  ARM_CLIENT_ID: {{ .Values.secret.data.armClientId | b64enc }}
  ARM_CLIENT_SECRET: {{ .Values.secret.data.armClientSecret }}
