---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wildcard-certificate
spec:
  refreshInterval: 1h0m0s

  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-subscription-key-vault

  target:
    name: wildcard-certificate
    creationPolicy: Owner

    template:
      type: kubernetes.io/tls
      data:
        ca.crt: ""

        tls.key: |
          {{ .tlskey | b64dec | toString }}

        tls.crt: |
          {{ .tlscert | b64dec | toString }}

  data:
    - secretKey: "tlskey"
      remoteRef:
        key: secret/wildcard-certificate-base64-encoded-key

    - secretKey: "tlscert"
      remoteRef:
        key: secret/wildcard-certificate-base64-encoded
