{{- if .Values.armAuth -}}
{{- if eq .Values.armAuth.type "servicePrincipal" -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: networking-appgw-k8s-azure-service-principal
spec:
  refreshInterval: 1h0m0s
  
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-subscription-key-vault

  target:
    name: networking-appgw-k8s-azure-service-principal

    creationPolicy: Owner
    
    template:
      type: Opaque

      data:
        armAuth.json: |
          {{`{
            "tenantId": "{{ .tenantId | toString }}",
            "subscriptionId": "{{ .subscriptionId | toString }}",
            "clientId": "{{ .clientId | toString }}",
            "clientSecret": "{{ .clientSecret | toString }}",
            "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
            "activeDirectoryGraphResourceId": "https://graph.windows.net/",
            "galleryEndpointUrl": "https://gallery.azure.com/",
            "managementEndpointUrl": "https://management.core.windows.net/",
            "resourceManagerEndpointUrl": "https://management.azure.com/",
            "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/"
          }`}}

  data:
    - secretKey: "tenantId"
      remoteRef:
        key: secret/arm-tenant-id

    - secretKey: "subscriptionId"
      remoteRef:
        key: secret/arm-subscription-id

    - secretKey: "clientId"
      remoteRef:
        key: secret/arm-client-id

    - secretKey: "clientSecret"
      remoteRef:
        key: secret/arm-client-secret
{{- end -}}
{{- end -}}
