letsencrypt:
  email: alerts@silvios.me

  servers:
    - name: production
      host: acme-v02
  
    - name: staging
      host: acme-staging-v02

  issuers:
    - name:  azure
      class: azure/application-gateway

    - name:  nginx
      class: nginx
