---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-tls-wildcard
  annotations:
    appgw.ingress.kubernetes.io/health-probe-interval: "30"
    appgw.ingress.kubernetes.io/health-probe-timeout: "30"
    appgw.ingress.kubernetes.io/health-probe-unhealthy-threshold: "3"
spec:
  ingressClassName: azure-application-gateway

  tls:
    - hosts:
        - argocd.{{ .Values.global.environment.domain }}
      secretName: wildcard-certificate

  rules:
    - host: argocd.{{ .Values.global.environment.domain }}
      http:
        paths:
          - backend:
              service:
                name: argocd-server
                port:
                  number: 443
            path: /
            pathType: ImplementationSpecific
