---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-tls-{{ .Values.global.environment.cluster.certificates.type }}-{{ .Values.global.environment.cluster.certificates.server }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"

    cert-manager.io/cluster-issuer: {{ .Values.global.environment.cluster.certificates.type }}-{{ .Values.global.environment.cluster.certificates.server }}-{{ .Values.global.environment.cluster.ingress.type }}

    external-dns.alpha.kubernetes.io/ttl: "3m"
    external-dns.alpha.kubernetes.io/target: gateway.{{ .Values.global.environment.id }}.{{ .Values.global.environment.domain }}
spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - argocd.{{ .Values.global.environment.id }}.{{ .Values.global.environment.domain }}
      secretName: argocd-server-tls-{{ .Values.global.environment.cluster.certificates.type }}-{{ .Values.global.environment.cluster.certificates.server }}

  rules:
    - host: argocd.{{ .Values.global.environment.id }}.{{ .Values.global.environment.domain }}
      http:
        paths:
          - backend:
              service:
                name: argocd-server
                port:
                  number: 443
            path: /
            pathType: ImplementationSpecific
