configs:
  params:
    server.insecure: false

server:
  ingress:
    enabled: true
    https: true
    hosts:
      - ${server_ingress_host}.${server_ingress_domain}
    ingressClassName: "nginx"
    pathType: ImplementationSpecific
    paths:
      - /
    tls:
      - secretName: argocd-secret
        hosts:
          - ${server_ingress_host}.${server_ingress_domain}
    annotations:
      cert-manager.io/cluster-issuer: ${server_ingress_issuer_name}
      external-dns.alpha.kubernetes.io/ttl: "1m"
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
