---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-infra
  namespace: {{ .Release.Namespace }}
spec:
  project: {{ .Values.project }}

  source:
    {{- toYaml .Values.source | nindent 4 }}
    helm:
      values: |
        environment:
          {{- toYaml $.Values.environment | nindent 10 }}
        project: {{ $.Values.project }}
        source:
          repoURL: {{ $.Values.source.repoURL }}
          targetRevision: {{ $.Values.source.targetRevision }}

      {{- if $.Values.helm }}
      valueFiles:
        {{- range $.Values.helm.files }}
        - {{ . }}
        {{- end }}
      {{- end }}

  destination:
    name: {{ .Values.destination.name }}
    namespace: {{ .Release.Namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
